"""
plot images generated by the world using plt.imshow
"""

import yaml
import matplotlib.pyplot as plt

from polyominoworld.utils import get_leftout_positions
from polyominoworld.dataset import DataSet
from polyominoworld.world import World
from polyominoworld.params import Params
from polyominoworld.params import param2requests, param2default

from ludwig.results import gen_param_paths


if __name__ == '__main__':

    project_name = 'PolyominoWorld'
    for param_path, label in gen_param_paths(
            project_name,
            param2requests,
            param2default,
            # isolated=True,
            # runs_path=Path(__file__).parent.parent / 'runs',
    ):

        # load hyper-parameter settings
        with (param_path / 'param2val.yaml').open('r') as f:
            param2val = yaml.load(f, Loader=yaml.FullLoader)
        params = Params.from_param2val(param2val)

        # re-generate data  the way it was during training
        world = World(params)
        data = DataSet(world.generate_sequences(leftout_colors=(),
                                                leftout_shapes=(),
                                                leftout_variants='',
                                                leftout_positions=get_leftout_positions(''),
                                                ),
                       seed=params.seed,
                       shuffle_events=params.shuffle_events,
                       shuffle_sequences=params.shuffle_sequences,
                       name='re-generated')

        event = data.get_events()[0]

        # valid range for imshow with RGB data is [0..1] so negative floats are not allowed.

        # plot
        image = event.world_vector.as_3d().swapaxes(0, -1).swapaxes(0, 1)
        plt.imshow(image)  # expects the input data array size to be X x Y x 3
        plt.axis("off")
        plt.show()
